### ISSUE TITLE
Feedback tool not working on dev, stage environments

### ISSUE THREAD

**Issue by lbeaufort** [18F/openFEC#2713]
The "Feedback" tool isn't working on [dev](https://fec-dev-proxy.app.cloud.gov/) or [stage](https://fec-stage-proxy.app.cloud.gov/):

When I try "Test" "Test" "Test", I get the following error: ![image.png](https://images.zenhubusercontent.com/59a579f28f62dc7798c47359/2ea0094b-29b6-45d8-9fa3-4458e637354e)

On my local machine, I have the same error and the error that displays is: 
Internal Server Error: /data/issue/
Traceback (most recent call last):
  File "/Users/<USERNAME>/dev/cms/.env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Users/<USERNAME>/dev/cms/.env/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/Users/<USERNAME>/dev/cms/.env/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/<USERNAME>/dev/cms/.env/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/<USERNAME>/dev/cms/fec-cms/fec/data/views.py", line 447, in feedback
    data = json.loads(request.body)
  File "/Users/<USERNAME>/.pyenv/versions/3.5.4/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
Internal Server Error: /data/issue/
Traceback (most recent call last):
  File "/Users/<USERNAME>/dev/cms/.env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Users/<USERNAME>/dev/cms/.env/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/Users/<USERNAME>/dev/cms/.env/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/<USERNAME>/dev/cms/.env/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/<USERNAME>/dev/cms/fec-cms/fec/data/views.py", line 447, in feedback
    data = json.loads(request.body)
  File "/Users/<USERNAME>/.pyenv/versions/3.5.4/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

**Comment by lbeaufort** [comment]
@patphongs FYI

**Comment by lbeaufort** [comment]
Resolved by PR: https://github.com/18F/fec-cms/pull/1387
